has_header:
  # sensor_msgs
  - sensor_msgs/msg/Image
  - sensor_msgs/msg/CompressedImage
  - sensor_msgs/msg/CameraInfo
  - sensor_msgs/msg/PointCloud2
  - sensor_msgs/msg/LaserScan
  - sensor_msgs/msg/Imu
  - sensor_msgs/msg/NavSatFix
  - sensor_msgs/msg/MagneticField
  - sensor_msgs/msg/FluidPressure
  - sensor_msgs/msg/Illuminance
  - sensor_msgs/msg/RelativeHumidity
  - sensor_msgs/msg/Temperature
  - sensor_msgs/msg/Range
  - sensor_msgs/msg/PointCloud
  
  # geometry_msgs
  - geometry_msgs/msg/PoseStamped
  - geometry_msgs/msg/TwistStamped
  - geometry_msgs/msg/AccelStamped
  - geometry_msgs/msg/Vector3Stamped
  - geometry_msgs/msg/PointStamped
  - geometry_msgs/msg/QuaternionStamped
  - geometry_msgs/msg/TransformStamped
  - geometry_msgs/msg/WrenchStamped
  
  # nav_msgs
  - nav_msgs/msg/OccupancyGrid
  - nav_msgs/msg/GridCells
  - nav_msgs/msg/Path
  - nav_msgs/msg/Odometry
  
  # visualization_msgs
  - visualization_msgs/msg/Marker
  - visualization_msgs/msg/MarkerArray
  - visualization_msgs/msg/InteractiveMarker
